### ISSUE TITLE
Share Story Behind Why You Created This Validator?

### ISSUE THREAD

**Issue by kinlane** [codekie/openapi-examples-validator#129]
Hey Now! I am just looking for more of the story behind why you created this validator so I can use quote / snippet in storytelling around OpenAPI specification as part of the OAI -- showcasing the useful tools people are building around the space.

**Comment by codekie** [comment]
Hi @kinlane

When we started to use RESTful APIs more heavily, we were looking for a proper interface description language to describe our APIs. After evaluating available options, we decided to use the OpenAPI specification (back then it still was called "Swagger specification").

As one of the biggest benefits of having a well described API is that the frontend-developers can start with the development even when the backend is not available (yet) or the development of the backend hasn't even started yet. For the development of the frontend as well as for the functional automated tests, we used a mock-server which simply served static example-files that were compliant to the API-description. Since these example-files played such a central role, it was crucial to us that they were and would remain valid in the ongoing development process, as these application are extended continuously.

Unfortunately, the OpenAPI-specification itself does not require associated examples to be valid and I couldn't find any tools that would validate these examples against the API description. So I wrote my own tool ... That's how version 1 of the `openapi-examples-validator` was born.
