### ISSUE TITLE
Do you plan to continue this project?

### ISSUE THREAD

**Issue by marc0l92** [codekie/openapi-examples-validator#168]
Hello,
I would like to use this library in my company, but since there are no updates since a while, I was wandering if you plan to support it.

Thanks

**Comment by codekie** [comment]
Hi @marc0l92 . Thanks for your interest. Yes I do plan to continue this project. In fact, there already are unfinished changes that have not been pushed yet. Unfortunately, due to my workload, currently I can't give it the attention it deserves.

However, since we also heavily use this tool in our company, there are no intentions to abandon it.

**Comment by marc0l92** [comment]
Can I submit some pull requests to add some features I need for my project?
I see some really old pull request in this repository (one year old), so I'm worried they can take some time before been meged

**Comment by codekie** [comment]
Yes, you can. Given that it does not contain breaking changes and the pull request includes the automated tests to cover the new feature and to ensure that the existing code works.

However, I'd recommend to create an issue for each pull request first, describing what they are about before pushing them. Just to make sure that there are no misunderstandings and to prevent the case that I reject a pull request after you've done your work if I don't see it fitting for this tool.

Also, please make sure that there is only one feature per pull request.
